scrape_configs:
  - job_name: 'config_server_metrics'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 3s
    static_configs:
      - targets: ['host.docker.internal:8888']
        labels:
          application: 'Config server application'