spring:
  # Basic app configuration
  application:
    name: "gateway"

  # Config server configuration
  config:
    import: "optional:configserver:http://localhost:8888/"

# Enable debug logging
logging:
  level:
    com:
      microforum:
        gateway:
          DEBUG