server:
  port: 9090

spring:
  application:
    name: api-gateway
  # Connect with service registry and locate services
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

# Eureka configurations
eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:7777/eureka/

# Application info (will be shown in eureka too)
info:
  app:
    name: "posts"
    description: "Posts service for micro-forum app"
    version: "1.0.0"

# Actuator configuration
management:
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    env:
      enabled: true
  # Enable gateway API
  endpoint:
    gateway:
      access: read_only

