spring:
  # Basic app configuration
  application:
    name: "gateway"
  # Config server configuration
  config:
    import: "optional:configserver:http://localhost:8888/"
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: "http://localhost:7080/realms/master/protocol/openid-connect/certs"
