# Profile config
spring:
  config:
    activate:
      on-profile: "dev"

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: "http://localhost:7080/realms/master/protocol/openid-connect/certs"