server:
  port: 9999

spring:
  # Connect with service registry and locate services
  reactor:
    # To let context propagate across asynchronous executions, thread boundaries, and even across different services (Security
    # credentials, Correlation ID, tracing requests across services, locale settings for internationalization
    context-propagation: auto
  cloud:
    gateway:
      # Service scan config
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      # Gateway request timeout settings
      httpclient:
        # Handshake timeout
        connect-timeout: 1000
        # Request processing timeout
        response-timeout: 2s

# Eureka configurations
eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:7777/eureka/

# Circuit breaker configurations
resilience4j.circuitbreaker:
  configs:
    default:
      slidingWindowSize: 10
      permittedNumberOfCallsInHalfOpenState: 2
      failureRateThreshold: 50
      waitDurationInOpenState: 10000
    postsCircuitBreaker: # Same name as mentioned in gateway custom route config
      failureRateThreshold: 30

# Application info (will be shown in eureka too)
info:
  app:
    name: "gateway"
    description: "API gateway service for micro-forum app"
    version: "1.0.0"

# Actuator configuration
management:
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    env:
      enabled: true

  # For tracing
  otlp:
    metrics:
      export:
        enabled: false
        step: 1m
        url: https://otlp.eu01.nr-data.net
  tracing:
    sampling:
      probability: 1.0f

  # Enable gateway API
  endpoint:
    gateway:
      access: read_only

# Enable debug logging
logging:
  level:
    com:
      microforum:
        gateway:
          DEBUG

constants:
  retry:
    maxAttempts: 3
    backoff:
      initial: 100
      max: 1000
      multiplier: 2
      multiplyPrevious: true