server:
  port: 3400

spring:
  cloud:
    # Functions integration
    function:
      definition: generateNotification|sendNotification

    # Stream binding configuration
    stream:
      bindings:
        # Binding #1 for getting notification input events
        generateNotificationsendNotification-in-0: # Same as the function as defined
          destination: send-notification # Exchange name
          group: ${spring.application.name} # Queue name suffix (send-notification.notification}

        # Binding #2 for publishing task complete events
        notificationDelivered-out-0: # Same as the function as defined
          destination: notification-delivered # Exchange name

  # RabbitMQ configuration
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    connection-timeout: 10s

# Service registry config
eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:7777/eureka/
