server:
  port: 3100

spring:
  # Basic app configuration
  application:
    version: 1.0.0
  # Profile config
  config:
    import:
      - "posts-dev.yml"
      - "posts-testing.yml"
      - "posts-prod.yml"

# Service registry config
eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:7777/eureka/

# Application info (will be shown in eureka too)
info:
  app:
    name: "posts"
    description: "Posts service for micro-forum app"
    version: "1.0.0"


# Swagger custom configuration: Show swagger Ui in root path
springdoc:
  swagger-ui:
    path: /

# Actuator configuration
management:
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    env:
      enabled: true
  # Enable shutdown endpoint
  endpoint:
    shutdown:
      enabled: true

# Expose shutdown endpoint
endpoints:
  shutdown:
    enabled: true
