server:
  port: 3100

spring:
  # Basic app configuration
  application:
    version: 1.0.0
  # Profile config
  config:
    import:
      - "posts-dev.yml"
      - "posts-testing.yml"
      - "posts-prod.yml"

# Swagger custom configuration: Show swagger Ui in root path
springdoc:
  swagger-ui:
    path: /

# Actuator configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,env
