# Profile config
spring:
  config:
    activate:
      on-profile: "prod"

  # Database configuration
  datasource:
    url: jdbc:postgresql://localhost:5432/post-service-pg-db
    username: post-service-pg-db_user
    password: post-service-pg-db_password

    # Connection pool configuration
    hikari:
      connection-timeout: 3000  # 3 seconds
      maximum-pool-size: 20     # Connection limit
      auto-commit: false        # Let us handle transactions
      idle-timeout: 60000       # 1 minute
      minimum-idle: 10          # Minimum number of idle connections in the pool

  # JPA configuration
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true