spring:
  # Basic app configuration
  application:
    name: "posts"

  # Config server configuration
  config:
    import: "optional:configserver:http://localhost:8888/"

  # Default active profile
  profiles:
    default: "dev"

  cloud:
    function:
      definition: handleDeliveredNotification

    stream:
      bindings:
        # Consumer configuration for 'notification-delivered' exchange
        handleDeliveredNotification-in-0:
          destination: notification-delivered
          group: ${spring.application.name}

        # Publisher configuration for 'send-notification' exchange
        notificationSender-out-0:
          destination: send-notification

  # RabbitMQ configuration
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    connection-timeout: 10s