spring:
  # Basic app configuration
  application:
    name: "posts"

  # Config server configuration
  config:
    import: "optional:configserver:http://localhost:8888/"

  # Default active profile
  profiles:
    default: "dev"
