# Profile config
spring:
  config:
    activate:
      on-profile: "testing"

  # Database configuration
  datasource:
    url: jdbc:postgresql://localhost:5432/post-service-pg-db
    username: post-service-pg-db_user
    password: post-service-pg-db_password

    # Connection pool configuration
    hikari:
      connection-timeout: 30000 # 30 seconds
      maximum-pool-size: 10     # Connection limit
      auto-commit: false        # Let us handle transactions
      idle-timeout: 600000      # 10 minutes
      minimum-idle: 3           # Minimum number of idle connections in the pool

  # JPA configuration
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true