version: '3'
services:
  other_external_rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"   # Main port for RabbitMQ (AMQP protocol)
      - "15672:15672" # Port for RabbitMQ Management Plugin (web UI)
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    hostname: rabbitmq